### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by fibo** [utrustdev/utrust-ts-library#4]
I am trying to implement a simple demo with React here: https://github.com/fibo/hello-utrust

I just added a `createOrder` to a submit button in a form but when I trigger it I get a CORS error.

The instructions about how to run the demo code are really simple and documented in the repo's README.

Can you please give me any hint?

**Comment by fibo** [comment]
![Screenshot 2021-02-08 at 00 38 55](https://user-images.githubusercontent.com/176730/107162809-07b93d00-69a6-11eb-8a67-1a98ae1f5887.png)

**Comment by TondaHack** [comment]
It looks like cors issue from browser. We don't allow cross-origin requests from browsers. It's in order to avoid the wrong usage of API. 

We don't recommend using this library in the frontend. That way your API_KEY can be visible to the public and abused. The purpose of this library is for backend usage. We'll update readme to clarify it better there.
